export { default as Header } from "./Navbar/Navbar"
export { default as Hero } from "./Sections/Hero/Hero"
export { default as Projects } from "./Sections/Projects/Projects"
export { default as Contact } from "./Sections/Contact/Contact"
export { default as About } from "./Sections/About/About"
export { default as Section } from "./Section"
